services:
 minecraft:
  image: itzg/minecraft-server
  volumes:
   - minecraftdata:/data
   - /home/ubuntu/minecraft-server/plugins:/plugins
  ports:
   - "25565:25565"
  environment:
    EULA: "TRUE"
    TYPE: "SPIGOT"
    OPS: "lukifasii"
    ENABLE_WHITELIST: "TRUE"
    ENFORCE_WHITELIST: "TRUE"
    EXEC_DIRECTLY: "TRUE"
  tty: true
  stdin_open: true
  restart: unless-stopped
volumes:
  minecraftdata:
    external: true